### ISSUE TITLE
error fetching OTP API:Not Found 

### ISSUE THREAD

**Issue by Uraniumknightofpotato** [vishalv26/covid-vaccine-booking#14]
error fetching OTP API:Not Found
can't fetch OTP in advance.bat, this occurs when we try to login for the 1st time to select the name..
OTP retriever app shows error that can't send the otp to the address

please sort this out...I have tried this in multiple PCs (Windows 10)

Thanks,
Have bought you a coffee too for your tremendous help. Just need the last booking for a family member

**Comment by vishalv26** [comment]
Ok Let me check.. will update you in some time

**Comment by vishalv26** [comment]
It should be fixed now. can you try and confirm?

**Comment by Uraniumknightofpotato** [comment]
should I download the code again?
coz without downloading the new one, the error still persists

**Comment by vishalv26** [comment]
Yes. There is new release Version 3.7

**Comment by Uraniumknightofpotato** [comment]
Hi,

Did download 3.7
still happening the same...sharing screenshots

**Comment by vishalv26** [comment]
No screenshot received yet

**Comment by Uraniumknightofpotato** [comment]
Have sent it with this email too

Although last email had them too... Let me know if you still don't receive
it...

We can share it through WhatsApp then if you are okay with it

**Comment by vishalv26** [comment]
Please use Github app or web and and submit from there. Thanks

**Comment by Uraniumknightofpotato** [comment]
![Capture 2](https://user-images.githubusercontent.com/85185907/120520194-23cb6900-c3f1-11eb-9c9c-7022866d2335.PNG)
![otp retriever error](https://user-images.githubusercontent.com/85185907/120520197-24fc9600-c3f1-11eb-98e2-33119e7162af.jpeg)

**Comment by vishalv26** [comment]
Can you try with different network it may be blocking kvdb.io

**Comment by Uraniumknightofpotato** [comment]
I am using jio... It is sending it through ifttt but still you need to fire the otp manually to the program on ifttt...

It was working fine till Sunday

**Comment by vishalv26** [comment]
I have also faced problem with jio when connecting to kvdb.io can you try with some other network?

**Comment by Uraniumknightofpotato** [comment]
hey, thanks...I was able to somehow book my last needed slot for now ...so when I need again, I will look out if the issue persists or not...thanks a lot, man
